# Generated by Django 4.1.7 on 2023-04-25 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('topic', models.TextField()),
                ('before', models.DateField()),
                ('after', models.DateField()),
                ('language', models.TextField()),
                ('country', models.TextField()),
                ('ceid', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('rss_link', models.TextField()),
                ('description', models.TextField()),
                ('source', models.TextField()),
                ('source_url', models.TextField()),
                ('pubdate', models.DateField()),
                ('query_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_data.query')),
            ],
        ),
    ]
