# Generated by Django 4.1.7 on 2023-05-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='after',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='before',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='ceid',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='query',
            name='country',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='query',
            name='language',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='query',
            name='query',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='query',
            name='topic',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='query',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AddConstraint(
            model_name='news',
            constraint=models.UniqueConstraint(fields=('title', 'source', 'pubdate'), name='unique_news'),
        ),
        migrations.AddConstraint(
            model_name='query',
            constraint=models.UniqueConstraint(fields=('query', 'before', 'after', 'language'), name='unique_query_time_language'),
        ),
    ]
