# Generated by Django 4.1.7 on 2023-05-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_data', '0002_alter_query_after_alter_query_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='after',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='query',
            name='before',
            field=models.DateField(),
        ),
    ]
