# Generated by Django 4.1.7 on 2023-05-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_data', '0003_alter_query_after_alter_query_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='has_polarization',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='rss_link',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='source_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
