# Generated by Django 4.1.7 on 2023-08-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_data', '0004_news_has_polarization_alter_news_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaggleNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('has_description', models.BooleanField(default=True)),
                ('category', models.TextField(default='BUSINESS')),
                ('source', models.TextField(default='')),
                ('pubdate', models.DateField()),
                ('country', models.TextField(choices=[('USA', 'Usa'), ('BRZ', 'Brz')], default='BRZ')),
                ('kaggle_url', models.TextField(default='')),
                ('has_polarization', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='kagglenews',
            constraint=models.UniqueConstraint(fields=('title', 'country'), name='unique_kaggle_news'),
        ),
    ]
