# Generated by Django 4.1.7 on 2023-08-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_data', '0005_kagglenews_kagglenews_unique_kaggle_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='kagglenews',
            name='kaggle_name',
            field=models.TextField(default=''),
        ),
    ]
