# Generated by Django 4.1.7 on 2023-08-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_data', '0006_kagglenews_kaggle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kagglenews',
            name='category',
            field=models.TextField(default='MISSING_CATEGORY'),
        ),
        migrations.AlterField(
            model_name='kagglenews',
            name='pubdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
