# Generated by Django 4.1.7 on 2023-08-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_data', '0007_alter_kagglenews_category_alter_kagglenews_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kagglenews',
            name='category',
            field=models.TextField(db_index=True, default='MISSING_CATEGORY'),
        ),
    ]
