# Generated by Django 4.1.7 on 2023-05-14 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news_data', '0003_alter_query_after_alter_query_before'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polarity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relevant_words', models.JSONField()),
                ('mean_polarization', models.FloatField()),
                ('polarization_list', models.JSONField()),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_data.news')),
            ],
        ),
        migrations.AddConstraint(
            model_name='polarity',
            constraint=models.UniqueConstraint(fields=('news_id',), name='one_to_one_news_to_polarity'),
        ),
    ]
