# Generated by Django 4.1.7 on 2023-05-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polarity',
            name='mean_polarization',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='polarity',
            name='polarization_list',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='polarity',
            name='relevant_words',
            field=models.JSONField(default=list),
        ),
    ]
