# Generated by Django 4.1.7 on 2023-05-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_processing', '0002_alter_polarity_mean_polarization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polarity',
            name='polarity_date',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
