# Generated by Django 4.1.7 on 2023-07-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_processing', '0004_remove_polarity_polarity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='polarity',
            name='news_pubdate',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polarity',
            name='news_query',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
