# Generated by Django 4.1.7 on 2023-07-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_processing', '0005_polarity_news_pubdate_polarity_news_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polarity',
            name='news_pubdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polarity',
            name='news_query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
