# Generated by Django 4.1.7 on 2023-08-20 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_data', '0007_alter_kagglenews_category_alter_kagglenews_pubdate'),
        ('lang_processing', '0006_alter_polarity_news_pubdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polarity',
            name='kagglenews_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_data.kagglenews'),
        ),
        migrations.AlterField(
            model_name='polarity',
            name='news_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_data.news'),
        ),
    ]
