# Generated by Django 4.1.7 on 2023-08-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_processing', '0008_polarity_sentic_polarization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polarity',
            name='sentic_polarization',
        ),
        migrations.AddField(
            model_name='polarity',
            name='sentic_polarization_list',
            field=models.JSONField(default=list),
        ),
    ]
